const stations = [
  { taxi: true, x: 1717, y: 103, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 1628, y: 179, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1710, y: 266, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1623, y: 342, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1546, y: 257, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1701, y: 430, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1448, y: 143, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1512, y: 87, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1761, y: 681, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1761, y: 516, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, bus: true, x: 1692, y: 594, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1614, y: 508, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 1536, y: 422, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1461, y: 332, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, bus: true, x: 1303, y: 163, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1189, y: 29, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1210, y: 155, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1218, y: 239, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1292, y: 325, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1372, y: 409, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, bus: true, x: 0, y: 0, taxiTo: [], metroTo: [], onibusTo: [], }
]


module.exports = { stations }