const stations = [
  { taxi: true, x: 1717, y: 103, taxiTo: [1, 7]},
  { subway: true, taxi: true, bus: true, x: 1628, y: 179, taxiTo: [0, 2, 4, 7], metroTo: [12, 35], onibusTo: [14, 12]},
  { taxi: true, x: 1710, y: 266, taxiTo: [1, 3]},
  { taxi: true, x: 1623, y: 342, taxiTo: [2, 4, 5, 12] },
  { taxi: true, x: 1546, y: 257, taxiTo: [1, 3, 6, 13]},
  { taxi: true, x: 1701, y: 430, taxiTo: [3, 9, 11]},
  { taxi: true, x: 1448, y: 143, taxiTo: [4, 7, 14]},
  { taxi: true, x: 1512, y: 87, taxiTo: [0, 1, 6, 98]},
  { taxi: true, x: 1761, y: 681, taxiTo: [10, 23]},
  { taxi: true, x: 1761, y: 516, taxiTo: [5, 10]},
  { taxi: true, bus: true, x: 1692, y: 594, taxiTo: [8, 9, 11, 22], onibusTo: [12, 24]},
  { taxi: true, x: 1614, y: 508, taxiTo: [5, 10, 12, 21]},
  { subway: true, taxi: true, bus: true, x: 1536, y: 422, taxiTo: [3, 11, 13, 20], metroTo: [1, 24, 29], onibusTo: [10, 1, 28], },
  { taxi: true, x: 1461, y: 332, taxiTo: [4, 12, 14, 19]},
  { taxi: true, bus: true, x: 1303, y: 163, taxiTo: [6, 13, 17],onibusTo: [1, 18, 34] },
  { taxi: true, x: 1189, y: 29, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1210, y: 155, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1218, y: 239, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 1292, y: 325, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1372, y: 409, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1450, y: 497, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1527, y: 583, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1602, y: 669, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1680, y: 757, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, subway: true, taxi: true, x: 1595, y: 835, taxiTo: [], metroTo: [12], onibusTo: [10], },
  { taxi: true, x: 1519, y: 751, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1441, y: 663, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1364, y: 576, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 1277, y: 654, taxiTo: [], metroTo: [], onibusTo: [12], },
  { subway: true, taxi: true, x: 1200, y: 567, taxiTo: [], metroTo: [12], onibusTo: [], },
  { subway: true, taxi: true, x: 1132, y: 316, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1366, y: 57, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1288, y: 490, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1122, y: 480, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 1052, y: 229, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, subway: true, taxi: true, x: 1009, y: 187, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1673, y: 922, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1354, y: 741, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1207, y: 401, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1432, y: 828, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1507, y: 915, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1269, y: 819, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1344, y: 905, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1045, y: 395, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 959, y: 473, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1754, y: 844, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1192, y: 731, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1113, y: 644, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1028, y: 721, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 1035, y: 557, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1182, y: 897, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, subway: true, taxi: true, x: 1020, y: 887, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1105, y: 809, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 952, y: 635, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 866, y: 713, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 873, y: 549, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 788, y: 627, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 779, y: 792, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 941, y: 800, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 855, y: 877, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 690, y: 872, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 711, y: 540, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, x: 795, y: 462, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 881, y: 388, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 968, y: 308, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 876, y: 240, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, subway: true, taxi: true, x: 649, y: 139, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 650, y: 285, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 718, y: 378, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 633, y: 454, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 555, y: 367, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 545, y: 533, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 466, y: 445, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 878, y: 99, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 708, y: 165, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 932, y: 953, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 765, y: 954, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 600, y: 949, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 518, y: 862, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 701, y: 706, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 624, y: 619, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 532, y: 699, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 609, y: 785, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 445, y: 779, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 355, y: 854, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 444, y: 778, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway:true, taxi: true, x: 433, y: 941, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 456, y: 610, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 366, y: 689, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 388, y: 360, taxiTo: [], metroTo: [], onibusTo: [], },
  { subway: true, taxi: true, x: 299, y: 417, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, x: 37, y: 571, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 201, y: 680, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 287, y: 606, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 478, y: 282, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 586, y: 205, taxiTo: [], metroTo: [], onibusTo: [], },
  { bus: true, taxi: true, x: 779, y: 326, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 379, y: 526, taxiTo: [], metroTo: [], onibusTo: [], },
  { taxi: true, x: 1444, y: 30, taxiTo: [], metroTo: [], onibusTo: [], }
]


module.exports = { stations }